name: ZoneMines
version: '1.0'
main: org.gustaav.zoneMines.ZoneMines
api-version: '1.21'
dependencies:
  server:
    Multiverse-Core:
      load: BEFORE
    Vault:
      load: BEFORE
    ZoneEconomy:
      load: BEFORE
    ZoneEnchants:
      load: BEFORE
    ZoneBoosters:
      load: BEFORE
    Citizens:
      load: BEFORE